env = XCURSOR_SIZE,18
env = HYPRCURSOR_SIZE,18
env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORMTHEME,qt6ct
env = XCURSOR_THEME,Bibata-Modern-Classic

general {
    gaps_in = 0
    gaps_out = 0
    border_size = 3
    col.active_border = rgba(142,0,0,1) rgba(0,0,0,1) 45deg
    col.inactive_border = rgba(595959aa)
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 0
    active_opacity = 1.0
    inactive_opacity = 0.8 
    shadow {
        enabled = false
    }
    blur {
        enabled = false
    }
}

animations {
    enabled = yes
    bezier = easeOutQuint,0.23,1,0.32,1
    bezier = quick,0.15,0,0.1,1
    animation = global, 1, 3, default
    animation = windows, 1, 3, easeOutQuint
    animation = windowsIn, 1, 3, easeOutQuint, popin 87%
    animation = windowsOut, 1, 2, quick, popin 87%
    animation = fadeIn, 1, 2, default
    animation = fadeOut, 1, 2, default
    animation = workspaces, 1, 2, default, fade
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    vfr = true 
}
