exec-once = sleep 2 &&  waybar
exec-once = dunst
exec-once = swaybg -i /home/kr8zy/Downloads/ar8ch_1.png -m fill
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Classic'
exec-once = gsettings set org.gnome.desktop.interface cursor-size 24
