windowrulev3 = opacity 0.85 0.75, class:^(kitty)$
windowrulev3 = opacity 0.85 0.75, title:^(.*zsh.*)$
windowrulev3 = suppressevent maximize, class:.*
layerrulev3 = dimaround, .*wofi.*
layerrulev3 = rounding 20, wofi
