background {
	monitor =
	path = /home/kr8zy/Downloads/ar8ch_1.png
	blur_passes = 4
	blur_size = 4
}

input-field {
	monitor =
	size = 250, 40
	outline_thickness = 2
	dots_size = 0.25
	dots_spacing = 0.35
	dots_center = true
	fade_on_empty = false

	placeholder_text = Oh my lord, I'm the gatekeeper

	outer_color = rgba(0,0,0,1)
	inner_color = rgba(142,0,0,1)
	font_color = rgba(255,255,255,1.0)
	
	check_color = rgba(0,200,0,0.8)
	fail_color = rgba(200,0,0,0.8)
	capslock_color = rgba(255,255,0,0.8)
}

label {
	monitor = 
	text = $TIME
	font_size = 80
	color = rgba(0,0,0,1)
	position = 0, -100
	valign = center
	halign = center
}

label {
	monitor =
	text = "You either win or learn"
	font_size = 16
	color = rgba(255,255,255,0.3)
	position = 0, 150
	valign = center
	halign = center
}

shape {
    monitor =
    size = 280, 40
    color = rgba(0,0,0,0.25)
    rounding = 24
    border_size = 2
    border_color = rgba(200,0,0,0.8)
    rotate = 0
    xray = false
    position = 0, 150
    valign = center
    halign = center
}
