$mainMod = SUPER
$terminal = kitty
$menu = wofi --show drun

env = XDG_RUNTIME_DIR,/run/user/1000
ecosystem:no_update_news = true

source = ~/.config/hypr/hyprland/modules/monitor.conf
source = ~/.config/hypr/hyprland/modules/input.conf
source = ~/.config/hypr/hyprland/modules/appearence.conf
source = ~/.config/hypr/hyprland/modules/windowrules.conf
source = ~/.config/hypr/hyprland/modules/binds.conf
source = ~/.config/hypr/hyprland/modules/exec.conf
